BaseMoney: 10.00
# How much to give on the first thank to a player

RepeatedThankRatio: 0.9
# >1: Thanking the same player multiple times gives more money each time
# 1: Thanking the same player multiple times always gives BaseMoney
# >0 and <1: Thanking the same player multiple times gives less money each time
# 0: Thanking the same player multiple times will only run ThankCommands
# <0: Thanking the same player multiple times will tell the player CantThankSamePlayerMessage

ThankCooldown: 3600
# Cooldown in order to use /thank again (in seconds)

ThankCommands:
  - "bcast &a%THANKER% &2just thanked &a%THANKEE%&2%REASON%."

DenyThankingSameIP: true
DenyThankingCooldownPlayers: false
DenyThank4Thank: true

CooldownMessage: "&cYou cannot use that command for another %TIME%."
NoPermissionMessage: "&cYou do not have permission to use that command."

ThankcountFromMessage: "&a%THANKER% has thanked %COUNT% times."
ThankcountToMessage: "&a%THANKEE% has been thanked %COUNT% times."
ThankcountFromToMessage: "&a%THANKER% has thanked %THANKEE% %COUNT% times."

CantThankOfflinePlayerMessage: "&cYou cannot thank a player who is offline."
CantThankSelfMessage: "&cYou cannot thank yourself."
CantThankSamePlayerMessage: "&cYou cannot thank the same player more than once."
CantThankSameIPMessage: "&cYou cannot thank that player because they share the same IP as you."
CantThankCooldownMessage: "&cYou cannot thank a player who recently thanked a player."
CantThank4ThankMessage: "&cYou cannot thank that player because thank4thank has been detected."
